# Generated by Django 4.2.7 on 2024-01-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Manager_app', '0002_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Description',
            field=models.TextField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
