# Generated by Django 4.2.7 on 2024-01-22 19:02

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Task_Manager_app', '0005_delete_taskuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Category',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task_Manager_app.category')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='Category',
            field=models.ManyToManyField(to='Task_Manager_app.category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task_Manager_app.user'),
        ),
    ]
