# Generated by Django 4.2.7 on 2024-01-22 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Task_Manager_app', '0009_remove_task_category_task_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='User',
        ),
        migrations.AddField(
            model_name='category',
            name='User',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
