# Generated by Django 4.2.7 on 2024-01-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Manager_app', '0015_alter_task_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Tag',
            field=models.CharField(choices=[('High Priority', 'High Priority'), ('Medium Priority', 'Medium Priority'), ('Low Priority', 'Low Priority'), ('No Priority', 'No Priority')], default='No Priority', max_length=16),
        ),
    ]
